CC = g++
CFLAGS = -O2

iconvtest: iconvtest.cpp ../../source/utf8.h timer.h ../../source/utf8/core.h ../../source/utf8/checked.h ../../source/utf8/unchecked.h
	$(CC) $(CFLAGS) iconvtest.cpp -oiconvtest
